### ISSUE TITLE
Extend reservation functionality

### ISSUE THREAD

**Issue by ImLecus** [ImLecus/JavaPL2#28]
Reservations should be saved and be visualized by an administrator. Also, if the building has a reservation active in the time lapse the client wants, the reservation button should be disabled.

**Comment by ImLecus** [comment]
Features needed to finish this issue:
* Admin should view the user reservations
* Hosts should view their building reservations
* Users should vew their reservations and cancel them

**Comment by Promete04** [comment]
Features needed to finish this issue:
* Admin should view the user reservations
